<a href="https://colab.research.google.com/github/DuwiDieDataDoring/EduardRepo/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Usual Suspects
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import nltk
from sklearn.preprocessing import StandardScaler,RobustScaler
from sklearn.pipeline import make_pipeline

In [0]:
train = pd.read_csv('../training.csv')
test = pd.read_csv('../test.csv')

In [52]:
train

              TransactionId         BatchId  ... PricingStrategy FraudResult
0       TransactionId_76871   BatchId_36123  ...               2           0
1       TransactionId_73770   BatchId_15642  ...               2           0
2       TransactionId_26203   BatchId_53941  ...               2           0
3         TransactionId_380  BatchId_102363  ...               2           0
4       TransactionId_28195   BatchId_38780  ...               2           0
5       TransactionId_23223   BatchId_25954  ...               2           0
6      TransactionId_118063  BatchId_118460  ...               4           0
7      TransactionId_100640   BatchId_38561  ...               2           0
8       TransactionId_51905   BatchId_93774  ...               2           0
9      TransactionId_130161   BatchId_82409  ...               2           0
10      TransactionId_51800  BatchId_112288  ...               2           0
11      TransactionId_33857  BatchId_126394  ...               2           0
12      TransactionId_94963  BatchId_104726  ...               2           0
13     TransactionId_104687   BatchId_59433  ...               2           0
14      TransactionId_86903   BatchId_59433  ...               2           0
15     TransactionId_118831   BatchId_59433  ...               2           0
16     TransactionId_122975   BatchId_31312  ...               2           0
17      TransactionId_98367    BatchId_6789  ...               2           0
18      TransactionId_64044  BatchId_117733  ...               2           0
19     TransactionId_119821   BatchId_89644  ...               4           0
20      TransactionId_94363   BatchId_94932  ...               2           0
21      TransactionId_93543  BatchId_103527  ...               4           0
22     TransactionId_138139    BatchId_8334  ...               2           0
23      TransactionId_79885   BatchId_48769  ...               2           0
24     TransactionId_127132   BatchId_50160  ...               2           0
25      TransactionId_74649  BatchId_100266  ...               2           0
26       TransactionId_7396  BatchId_124231  ...               2           0
27     TransactionId_126754   BatchId_60208  ...               2           0
28     TransactionId_136360   BatchId_48611  ...               2           0
29      TransactionId_89705   BatchId_16332  ...               2           0
...                     ...             ...  ...             ...         ...
95632   TransactionId_70563    BatchId_2831  ...               2           0
95633   TransactionId_66516   BatchId_98969  ...               2           0
95634    TransactionId_5394  BatchId_121783  ...               4           0
95635   TransactionId_11513   BatchId_25909  ...               4           0
95636  TransactionId_112982  BatchId_108518  ...               2           0
95637   TransactionId_53307  BatchId_136096  ...               2           0
95638   TransactionId_20690   BatchId_18591  ...               2           0
95639   TransactionId_73868   BatchId_94787  ...               2           0
95640  TransactionId_131580   BatchId_16209  ...               2           0
95641  TransactionId_134543   BatchId_88196  ...               2           0
95642  TransactionId_117975   BatchId_55755  ...               2           0
95643  TransactionId_114220   BatchId_89378  ...               2           0
95644   TransactionId_49819  BatchId_127156  ...               2           0
95645  TransactionId_131922   BatchId_69178  ...               1           0
95646  TransactionId_128602   BatchId_88013  ...               2           0
95647   TransactionId_74925   BatchId_29059  ...               2           0
95648   TransactionId_96153   BatchId_24311  ...               2           0
95649  TransactionId_138376  BatchId_107100  ...               2           0
95650   TransactionId_36354   BatchId_81234  ...               2           0
95651   TransactionId_16042   BatchId_49303  ...               2           0
95652   TransactionId_71994   BatchId_66957  ...               2           0
95653   TransactionId_68851  BatchId_100900  ...               2           0
95654   TransactionId_18130   BatchId_20310  ...               2           0
95655   TransactionId_38907   BatchId_92168  ...               2           0
95656   TransactionId_68402   BatchId_17092  ...               2           0
95657   TransactionId_89881   BatchId_96668  ...               2           0
95658   TransactionId_91597    BatchId_3503  ...               2           0
95659   TransactionId_82501  BatchId_118602  ...               2           0
95660  TransactionId_136354   BatchId_70924  ...               2           0
95661   TransactionId_35670   BatchId_29317  ...               2           0

[95662 rows x 16 columns]

In [53]:
train.corr()

                 CountryCode    Amount     Value  PricingStrategy  FraudResult
CountryCode              NaN       NaN       NaN              NaN          NaN
Amount                   NaN  1.000000  0.989692        -0.061931     0.557370
Value                    NaN  0.989692  1.000000        -0.017020     0.566739
PricingStrategy          NaN -0.061931 -0.017020         1.000000    -0.033821
FraudResult              NaN  0.557370  0.566739        -0.033821     1.000000

In [0]:
train_features = train.drop('FraudResult', axis = 1)
y = train['FraudResult'].reset_index(drop=True)
test_features = test
features = pd.concat([train_features, test_features])

In [0]:
def remove_vocab(post):
    return ''.join(i for i in post if i.isdigit())

features['TransactionId'] = features['TransactionId'].apply(remove_vocab)
features['BatchId'] = features['BatchId'].apply(remove_vocab)
features['AccountId'] = features['AccountId'].apply(remove_vocab)
features['SubscriptionId'] = features['SubscriptionId'].apply(remove_vocab)
features['CustomerId'] = features['CustomerId'].apply(remove_vocab)
features['ProviderId'] = features['ProviderId'].apply(remove_vocab)
features['ProductId'] = features['ProductId'].apply(remove_vocab)
features['ChannelId'] = features['ChannelId'].apply(remove_vocab)

features['TransactionId'] = features['TransactionId'].astype(int)
features['BatchId']= features['BatchId'].astype(int)
features['AccountId'] = features['AccountId'].astype(int)
features['SubscriptionId'] = features['SubscriptionId'].astype(int)
features['CustomerId'] = features['CustomerId'].astype(int)
features['ProviderId'] = features['ProviderId'].astype(int)
features['ProductId'] = features['ProductId'].astype(int)
features['ChannelId'] = features['ChannelId'].astype(int)

In [56]:
features

       TransactionId  BatchId  ...  TransactionStartTime  PricingStrategy
0              76871    36123  ...  2018-11-15T02:18:49Z                2
1              73770    15642  ...  2018-11-15T02:19:08Z                2
2              26203    53941  ...  2018-11-15T02:44:21Z                2
3                380   102363  ...  2018-11-15T03:32:55Z                2
4              28195    38780  ...  2018-11-15T03:34:21Z                2
5              23223    25954  ...  2018-11-15T03:35:10Z                2
6             118063   118460  ...  2018-11-15T03:44:31Z                4
7             100640    38561  ...  2018-11-15T03:45:13Z                2
8              51905    93774  ...  2018-11-15T04:14:59Z                2
9             130161    82409  ...  2018-11-15T04:31:48Z                2
10             51800   112288  ...  2018-11-15T04:32:08Z                2
11             33857   126394  ...  2018-11-15T04:32:42Z                2
12             94963   104726  ...  2018-11-15T04:35:10Z                2
13            104687    59433  ...  2018-11-15T04:47:31Z                2
14             86903    59433  ...  2018-11-15T04:48:09Z                2
15            118831    59433  ...  2018-11-15T04:51:20Z                2
16            122975    31312  ...  2018-11-15T04:52:37Z                2
17             98367     6789  ...  2018-11-15T04:54:00Z                2
18             64044   117733  ...  2018-11-15T04:54:18Z                2
19            119821    89644  ...  2018-11-15T04:56:25Z                4
20             94363    94932  ...  2018-11-15T04:57:00Z                2
21             93543   103527  ...  2018-11-15T04:59:02Z                4
22            138139     8334  ...  2018-11-15T04:59:41Z                2
23             79885    48769  ...  2018-11-15T04:59:51Z                2
24            127132    50160  ...  2018-11-15T05:06:25Z                2
25             74649   100266  ...  2018-11-15T05:06:39Z                2
26              7396   124231  ...  2018-11-15T05:37:24Z                2
27            126754    60208  ...  2018-11-15T05:38:25Z                2
28            136360    48611  ...  2018-11-15T05:38:35Z                2
29             89705    16332  ...  2018-11-15T05:38:37Z                2
...              ...      ...  ...                   ...              ...
44989          59036    47763  ...  2019-03-14T23:39:47Z                2
44990          73940    48637  ...  2019-03-14T23:40:41Z                1
44991          71759   107072  ...  2019-03-14T23:41:02Z                2
44992         124192   135249  ...  2019-03-14T23:41:25Z                4
44993          58380    93461  ...  2019-03-14T23:42:09Z                1
44994         116667    76811  ...  2019-03-14T23:42:33Z                2
44995          60819     9494  ...  2019-03-14T23:43:26Z                1
44996          74223    17869  ...  2019-03-14T23:43:47Z                2
44997          56817    59158  ...  2019-03-14T23:44:46Z                1
44998         138266    18480  ...  2019-03-14T23:46:07Z                1
44999          17145   107570  ...  2019-03-14T23:48:07Z                1
45000          42734   108510  ...  2019-03-14T23:49:13Z                2
45001          51760     3837  ...  2019-03-14T23:49:34Z                1
45002          62677   133584  ...  2019-03-14T23:49:58Z                2
45003          14643   100536  ...  2019-03-14T23:50:08Z                2
45004          34876    29172  ...  2019-03-14T23:50:59Z                2
45005           9981   118185  ...  2019-03-14T23:51:15Z                2
45006          31273    65264  ...  2019-03-14T23:51:21Z                1
45007          68650   134224  ...  2019-03-14T23:51:43Z                2
45008           2604   121813  ...  2019-03-14T23:51:52Z                2
45009          46151    75172  ...  2019-03-14T23:53:01Z                1
45010         109121   102543  ...  2019-03-14T23:54:03Z                2
45011          30094    83188  ...  2019-03-14T23:54:36Z                1
45012          73077    55857  ...  2019-03-14T23:55:39Z                2
45013         135846    19757  ...  2019-03-14T23:56:06Z                1
45014         116198   117348  ...  2019-03-14T23:56:28Z                2
45015          24829    53630  ...  2019-03-14T23:57:38Z                1
45016         102920   112209  ...  2019-03-14T23:59:17Z                1
45017         128439    58734  ...  2019-03-14T23:59:39Z                2
45018          45927    98308  ...  2019-03-14T23:59:51Z                4

[140681 rows x 15 columns]

In [0]:
features = features.drop(['BatchId','AccountId','SubscriptionId','CustomerId','CurrencyCode','CountryCode','PricingStrategy','TransactionStartTime','ProductId','ProviderId','ChannelId'], axis = 1)

In [58]:
features

       TransactionId     ProductCategory   Amount  Value
0              76871             airtime   1000.0   1000
1              73770  financial_services    -20.0     20
2              26203             airtime    500.0    500
3                380        utility_bill  20000.0  21800
4              28195  financial_services   -644.0    644
5              23223             airtime   2000.0   2000
6             118063             airtime  10000.0  10000
7             100640  financial_services   -500.0    500
8              51905             airtime    500.0    500
9             130161  financial_services    600.0    600
10             51800             airtime    890.0    890
11             33857  financial_services    -40.0     40
12             94963  financial_services    600.0    600
13            104687  financial_services   4000.0   4000
14             86903  financial_services   4000.0   4000
15            118831  financial_services   4000.0   4000
16            122975  financial_services    500.0    500
17             98367        data_bundles   1000.0   1000
18             64044  financial_services    -10.0     10
19            119821             airtime    500.0    500
20             94363  financial_services    -25.0     25
21             93543             airtime    500.0    500
22            138139  financial_services    -25.0     25
23             79885             airtime   1000.0   1000
24            127132             airtime    500.0    500
25             74649  financial_services    -10.0     10
26              7396             airtime   1000.0   1000
27            126754                  tv   3500.0   3500
28            136360  financial_services    -70.0     70
29             89705  financial_services   2000.0   2000
...              ...                 ...      ...    ...
44989          59036  financial_services  -5000.0   5000
44990          73940             airtime  10000.0  10000
44991          71759  financial_services  -5000.0   5000
44992         124192             airtime -10000.0  10000
44993          58380             airtime  10000.0  10000
44994         116667  financial_services  -5000.0   5000
44995          60819             airtime  10000.0  10000
44996          74223  financial_services  -5000.0   5000
44997          56817             airtime  10000.0  10000
44998         138266             airtime  10000.0  10000
44999          17145             airtime  10000.0  10000
45000          42734  financial_services  -5000.0   5000
45001          51760             airtime  10000.0  10000
45002          62677  financial_services  -5000.0   5000
45003          14643  financial_services  10000.0  10000
45004          34876             airtime  10000.0  10000
45005           9981  financial_services  -5000.0   5000
45006          31273             airtime  10000.0  10000
45007          68650  financial_services  -5000.0   5000
45008           2604             airtime   5000.0   5000
45009          46151             airtime  10000.0  10000
45010         109121  financial_services  -5000.0   5000
45011          30094             airtime  10000.0  10000
45012          73077  financial_services  -5000.0   5000
45013         135846             airtime  10000.0  10000
45014         116198  financial_services  -5000.0   5000
45015          24829             airtime  10000.0  10000
45016         102920             airtime  10000.0  10000
45017         128439  financial_services  -5000.0   5000
45018          45927             airtime   3500.0   3500

[140681 rows x 4 columns]

In [0]:
final_features = pd.get_dummies(features)

In [60]:
final_features

       TransactionId   Amount  ...  ProductCategory_tv  ProductCategory_utility_bill
0              76871   1000.0  ...                   0                             0
1              73770    -20.0  ...                   0                             0
2              26203    500.0  ...                   0                             0
3                380  20000.0  ...                   0                             1
4              28195   -644.0  ...                   0                             0
5              23223   2000.0  ...                   0                             0
6             118063  10000.0  ...                   0                             0
7             100640   -500.0  ...                   0                             0
8              51905    500.0  ...                   0                             0
9             130161    600.0  ...                   0                             0
10             51800    890.0  ...                   0                             0
11             33857    -40.0  ...                   0                             0
12             94963    600.0  ...                   0                             0
13            104687   4000.0  ...                   0                             0
14             86903   4000.0  ...                   0                             0
15            118831   4000.0  ...                   0                             0
16            122975    500.0  ...                   0                             0
17             98367   1000.0  ...                   0                             0
18             64044    -10.0  ...                   0                             0
19            119821    500.0  ...                   0                             0
20             94363    -25.0  ...                   0                             0
21             93543    500.0  ...                   0                             0
22            138139    -25.0  ...                   0                             0
23             79885   1000.0  ...                   0                             0
24            127132    500.0  ...                   0                             0
25             74649    -10.0  ...                   0                             0
26              7396   1000.0  ...                   0                             0
27            126754   3500.0  ...                   1                             0
28            136360    -70.0  ...                   0                             0
29             89705   2000.0  ...                   0                             0
...              ...      ...  ...                 ...                           ...
44989          59036  -5000.0  ...                   0                             0
44990          73940  10000.0  ...                   0                             0
44991          71759  -5000.0  ...                   0                             0
44992         124192 -10000.0  ...                   0                             0
44993          58380  10000.0  ...                   0                             0
44994         116667  -5000.0  ...                   0                             0
44995          60819  10000.0  ...                   0                             0
44996          74223  -5000.0  ...                   0                             0
44997          56817  10000.0  ...                   0                             0
44998         138266  10000.0  ...                   0                             0
44999          17145  10000.0  ...                   0                             0
45000          42734  -5000.0  ...                   0                             0
45001          51760  10000.0  ...                   0                             0
45002          62677  -5000.0  ...                   0                             0
45003          14643  10000.0  ...                   0                             0
45004          34876  10000.0  ...                   0                             0
45005           9981  -5000.0  ...                   0                             0
45006          31273  10000.0  ...                   0                             0
45007          68650  -5000.0  ...                   0                             0
45008           2604   5000.0  ...                   0                             0
45009          46151  10000.0  ...                   0                             0
45010         109121  -5000.0  ...                   0                             0
45011          30094  10000.0  ...                   0                             0
45012          73077  -5000.0  ...                   0                             0
45013         135846  10000.0  ...                   0                             0
45014         116198  -5000.0  ...                   0                             0
45015          24829  10000.0  ...                   0                             0
45016         102920  10000.0  ...                   0                             0
45017         128439  -5000.0  ...                   0                             0
45018          45927   3500.0  ...                   0                             0

[140681 rows x 13 columns]

In [61]:
X = final_features[:len(y)]
test_X = final_features[len(X):]
X.head()

   TransactionId   Amount  ...  ProductCategory_tv  ProductCategory_utility_bill
0          76871   1000.0  ...                   0                             0
1          73770    -20.0  ...                   0                             0
2          26203    500.0  ...                   0                             0
3            380  20000.0  ...                   0                             1
4          28195   -644.0  ...                   0                             0

[5 rows x 13 columns]

In [62]:
X.drop(['TransactionId'], axis=1, inplace=True)
test_X.drop(['TransactionId'], axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [0]:
X_train = X
X_test = test_X
y_train = y

In [64]:

model_class = RandomForestClassifier()

model = make_pipeline(RobustScaler(), model_class)

model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Pipeline(memory=None,
         steps=[('robustscaler',
                 RobustScaler(copy=True, quantile_range=(25.0, 75.0),
                              with_centering=True, with_scaling=True)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [65]:
pred = model.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [0]:
submission = pd.DataFrame({'TransactionId':test['TransactionId'], 'Fraudulent':pred})
submission.to_csv('submission.csv', index=False)

Honour Code

I Eduard Senekal confirm - by submitting my - that the solutions in this notebook are a result of my own work and that I abide by the EDSA honour code (https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.